version: "3.8"

services:
  app:
    container_name: "app"
    build:
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/recruitment_task?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.username": "rt_user",
        "spring.datasource.password": "secret",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    depends_on:
      - "mysqldb"

  mysqldb:
    container_name: "mysqldb"
    image: "mysql"
    environment:
      - "MYSQL_USER=rt_user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=recruitment_task"
    ports:
      - "3306:3306"
    expose:
      - "3306"